
name: CICD

on:
  push:
    branches: [ master ]  

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        
      - name: Set Node.js 16.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x

      - name: Build Project
        run: |
            npm ci
            npm run build --if-present
            
      - name: Test Project     
        run: npm test 
            